# Generated by Django 5.1.7 on 2025-03-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='destination',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='pickup_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
    ]
