# Generated by Django 5.1.7 on 2025-03-16 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_passenger_user_alter_passenger_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='preferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
